# project docker-compose

version: "3"

services:
    influxdb:
        image: influxdb:2.1.1
        container_name: influxdb
        ports:
            - "8086:8086"
#        volumes:
#            - $PWD/influxdb.conf:/root/influxdb/influxdb.conf
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=admin2021
            - DOCKER_INFLUXDB_INIT_ORG=organization
            - DOCKER_INFLUXDB_INIT_BUCKET=initialBucket
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=thisShouldBeSecret
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8086"]
            interval: 30s
            timeout: 10s
            retries: 5

    app:
        build:
            context: .
        image: gerardovitale/influx-app
        container_name: influx-app
        environment:
            - INFLUXDB_INIT_ORG=organization
            - INFLUXDB_INIT_BUCKET=initialBucket
            - INFLUXDB_INIT_ADMIN_TOKEN=thisShouldBeSecret
        restart: on-failure
        depends_on:
            - influxdb
