# project docker-compose

version: "3"

services:
    influxdb:
        image: influxdb:2.1.1
        container_name: influxdb
        ports:
            - "8086:8086"
#        volumes:
#            - $PWD/influxdb.conf:/root/influxdb/influxdb.conf
        environment:
            - DOCKER_INFLUXDB_INIT_USERNAME="admin"         # The username to set for the system's initial super-user (Required).
            - DOCKER_INFLUXDB_INIT_PASSWORD="admin2021"     # The password to set for the system's initial super-user (Required).
            - DOCKER_INFLUXDB_INIT_ORG="organization"       # The name to set for the system's initial organization (Required).
            - DOCKER_INFLUXDB_INIT_BUCKET="initial_bucket"  # The name to set for the system's initial bucket (Required).
