# project docker-compose

version: "3"

services:
    influxdb:
        image: influxdb:2.1-alpine
        container_name: influxdb
        ports:
            - "8086:8086"
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
            - DOCKER_INFLUXDB_INIT_ORG=DemoOrganization
            - DOCKER_INFLUXDB_INIT_BUCKET=DemoBucket
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=thisShouldBeSecret
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8086"]
            interval: 30s
            timeout: 10s
            retries: 5

    telegraf:
        image: telegraf:1.19-alpine
        container_name: telegraf
        environment:
            - DOCKER_INFLUXDB_INIT_ORG=DemoOrganization
            - DOCKER_INFLUXDB_INIT_BUCKET=DemoBucket
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=thisShouldBeSecret
        volumes:
            - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        depends_on:
            - influxdb

    app:
        build:
            context: .
        image: gerardovitale/influx-app
        container_name: influx-app
        environment:
            - INFLUXDB_INIT_ORG=DemoOrganization
            - INFLUXDB_INIT_BUCKET=DemoBucket
            - INFLUXDB_INIT_ADMIN_TOKEN=thisShouldBeSecret
        restart: on-failure
        depends_on:
            - influxdb
